tasks:
  - name: Install Bun
    before: |
      curl -fsSL https://bun.sh/install | bash
      source /home/gitpod/.bashrc

image:
  file: .gitpod.Dockerfile

gitConfig:
  user.name: "Luan NGUYEN"
  user.email: "${GIT_COMMITTER_EMAIL}"
